
routes:
  - name: page#index
    url: /
    verb: GET

resources:
    accounts:
        url: /accounts
    folders:
        url: /accounts/{accountId}/folders
    messages:
        url: /accounts/{accountId}/folders/{folderId}/messages

